### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by EdwardLiao** [Kagami/boram#24]
I got some build errors after I try to "npm install". Is there anything else prior to this step? Thanks.

 
CXX(target) Release/obj.target/boram/src/mpv/interop.o
../src/mpv/interop.cc:8:10: fatal error: 'GLES2/gl2.h' file not found
#include <GLES2/gl2.h>
         ^
1 error generated.
make: *** [Release/obj.target/boram/src/mpv/interop.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/liaowei/.nvm/versions/node/v8.6.0/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Users/liaowei/.nvm/versions/node/v8.6.0/bin/node" "/Users/liaowei/.nvm/versions/node/v8.6.0/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/liaowei/temp/boram
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
✖ Install fail! Error: Run "sh -c node-gyp rebuild" error, exit code 1
Error: Run "sh -c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (/Users/liaowei/.nvm/versions/node/v8.6.0/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npminstall version: 3.1.4
npminstall args: /Users/liaowei/.nvm/versions/node/v8.6.0/bin/node /Users/liaowei/.nvm/versions/node/v8.6.0/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/liaowei/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://registry.npm.taobao.org

**Comment by EdwardLiao** [comment]
BTW, I build it on MacOSX

**Comment by Kagami** [comment]
You need to download [NaCl SDK](https://developer.chrome.com/native-client/sdk/download), install pepper49 and set `NACL_SDK_ROOT` environment variable to point to the dir of unpacked zip.
Also you will need to install mpv with its header files. You may use e.g. `brew install mpv`.

**Comment by EdwardLiao** [comment]
Thanks!

**Comment by emyarod** [comment]
@Kagami I'm running into a similar problem on Windows 10. Is this because of a faulty mpv installation? I have NaCl SDK pepper_49 and mpv installed but not sure what the cause of this error is.

```
$ npm install

> boram@0.3.7 install C:\Users\username\Documents\GitHub\boram
> node-gyp rebuild


C:\Users\username\Documents\GitHub\boram>if not defined npm_config_node_gyp (node "C:\Users\username\AppData\Roaming\nvm\v8.9.4\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\username\AppData\Roaming\nvm\v8.9.4\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  interop.cc
..\src\mpv\interop.cc(8): fatal error C1083: Cannot open include file: 'GLES2/gl2.h': No such file or directory [A :\Users\username\Documents\GitHub\boram\build\boram.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\username\AppData\Roaming\nvm\v8.9.4\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\nvm\\v8.9.4\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\username\Documents\GitHub\boram
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! boram@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the boram@0.3.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2018-01-29T22_48_40_694Z-debug.log
```

**Comment by Kagami** [comment]
You need to put NaCL SDK to C:\ on Windows, see [binding.gyp](https://github.com/Kagami/boram/blob/master/binding.gyp) for details.
Also, I'm using custom build of libvpx/ffmpeg/mpv compiled using [media-autobuild_suite](https://github.com/jb-alvarado/media-autobuild_suite) in order to avoid duplicated libav* libraries. I haven't published instructions/details but that repo has nice installation wizard so should be not too hard to build.
Also if you're on x64, you will need 64-bit NaCL binaries (by default only 32-bit included), see [here](https://github.com/Kagami/mpv.js#step-21-compile-64-bit-nacl-host-binaries-on-windows) for details.

**Comment by emyarod** [comment]
Thanks for the response, I am going to install NaCL SDK on C:\, in addition to the 64-bit NaCL binaries. Will media-autobuild_suite need to be installed on C:\ as well, or does that not matter?

**Comment by Kagami** [comment]
Yes, you need to clone media-autobuild_suite to `C:\mingw`

**Comment by emyarod** [comment]
hm I am getting a different error now

```
$ rm -rf node_modules/ && npm install
npm WARN deprecated eslint-plugin-class-property@1.1.0: please use eslint-plugin-babel and babel/semi

> electron@1.6.2 postinstall A:\Users\username\Documents\GitHub\boram\node_modules\electron
> node install.js


> boram@0.3.7 install A:\Users\username\Documents\GitHub\boram
> node-gyp rebuild


A:\Users\username\Documents\GitHub\boram>if not defined npm_config_node_gyp (node "C:\Users\username\AppData\Roaming\nvm\v8.9.4\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\username\AppData\Roaming\nvm\v8.9.4\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  interop.cc
..\src\mpv\interop.cc(17): fatal error C1083: Cannot open include file: 'mpv/client.h': No such file or directory
[A:\Users\username\Documents\GitHub\boram\build\boram.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\username\AppData\Roaming\nvm\v8.9.4\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\nvm\\v8.9.4\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd A:\Users\username\Documents\GitHub\boram
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! boram@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the boram@0.3.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2018-01-30T19_57_18_367Z-debug.log
```

**Comment by Kagami** [comment]
Have you installed media-autobuild_suite? You need to have mpv headers in `C:\mingw\local64\include`

**Comment by emyarod** [comment]
I cloned media-autobuild_suite into `C:\mingw` and ran `media-autobuild_suite.bat`. Is this the proper way to install media-autobuild_suite?

**Comment by Kagami** [comment]
Yes. Just select to compile libvpx, ffmpeg, mpv in its wizard and you should be fine.

**Comment by emyarod** [comment]
hm, it appears the wizard is erroring out during ffmpeg compilation with this:

```
 ffmpeg git ........................................ [Recently updated]
├ Changing options to comply to gplv3...
├ Compiling static FFmpeg...
├ Running configure...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config-flags=--static --enable-gmp --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-fontconfig --enable-gnutls --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-chromaprint --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-libopenh264 --enable-libopenmpt --enable-librtmp --enable-librubberband --enable-libssh --enable-libtesseract --enable-libxavs --enable-libxvid --enable-libzmq --enable-libzvbi --enable-opencl --enable-opengl --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBSSH_STATIC --extra-ldflags=-Wl,--allow-multiple-definition --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-version3 --disable-debug
ERROR: libopenmpt >= 0.2.6557 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
configure failed. Check C:/mingw/build/ffmpeg-git/build-static-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/sbLJ.zip
Copy and paste [logs.zip](https://0x0.st/sbLJ.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

These are the [logs.zip](https://0x0.st/sbLJ.zip). Not sure where to go from here

**Comment by Kagami** [comment]
Please create issue here https://github.com/jb-alvarado/media-autobuild_suite
They solve errors like this pretty fast.

**Comment by emyarod** [comment]
[looks like it was reported and fixed yesterday](https://github.com/jb-alvarado/media-autobuild_suite/issues/733)! However I'm now running into new problems when attempting to run some of your npm scripts. Might be because I am unfamiliar with electron or #19 but should I continue asking questions here or in a different thread?

**Comment by Kagami** [comment]
It's ok to ask here.

**Comment by emyarod** [comment]
I'm mostly not sure where to go now that I can install all the dependencies. If I `npm run start` then it seems to build the bundle, although with a few warnings. But `npm run dev` gives me an error saying libmpv is not installed, and nothing errored when I ran the media-autobuild_suite. Also `npm run app` tells me `'NODE_ENV' is not recognized as an internal or external command, operable program or batch file.`

**Comment by Kagami** [comment]
Try

```
node-gyp rebuild
npm start
npm run dev
```

**Comment by emyarod** [comment]
`node-gyp rebuild` seems to be fine. I get the same responses when I run `npm start` and `npm run dev` though

```
$ npm start

> boram@0.3.7 start A:\Users\username\Documents\GitHub\boram
> rm -rf dist && webpack --watch

Hash: c603a720ebec17fcaf74
Version: webpack 1.15.0
Time: 30733ms
                    Asset       Size  Chunks             Chunk Names
         roboto-light.ttf     351 kB          [emitted]
fontawesome-webfont.woff2    77.2 kB          [emitted]
               index.html  205 bytes          [emitted]
             icon-big.png    7.39 kB          [emitted]
           youtube-dl.zip    1.62 MB          [emitted]
             package.json   18 bytes          [emitted]
       roboto-regular.ttf     351 kB          [emitted]
        roboto-medium.ttf     350 kB          [emitted]
                 index.js    62.5 kB       0  [emitted]  index
              renderer.js    1.78 MB       1  [emitted]  renderer
                index.css    37.2 kB       1  [emitted]  renderer
    + 559 hidden modules

WARNING in ./~/electron-debug/index.js
Critical dependencies:
81:45-58 the request of a dependency is an expression
84:85-106 the request of a dependency is an expression
 @ ./~/electron-debug/index.js 81:45-58 84:85-106

WARNING in ./~/electron-debug/package.json
Module parse failed: A:\Users\username\Documents\GitHub\boram\node_modules\electron-debug\package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\lib\Parser.js:902:15)
    at NormalModule.<anonymous> (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\lib\NormalModule.js:104:16)
    at NormalModule.onModuleBuild (A:\Users\username\Documents\GitHub\boram\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (A:\Users\username\Documents\GitHub\boram\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at A:\Users\username\Documents\GitHub\boram\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.provide (A:\Users\username\Documents\GitHub\boram\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.readFile (A:\Users\username\Documents\GitHub\boram\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:140:24)
    at NormalModule.onLoadPitchDone (A:\Users\username\Documents\GitHub\boram\node_modules\webpack-core\lib\NormalModuleMixin.js:255:7)
    at NormalModule.loadPitch (A:\Users\username\Documents\GitHub\boram\node_modules\webpack-core\lib\NormalModuleMixin.js:182:27)
    at NormalModule.doBuild (A:\Users\username\Documents\GitHub\boram\node_modules\webpack-core\lib\NormalModuleMixin.js:241:4)
    at NormalModule.build (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\lib\NormalModule.js:84:14)
    at Compilation.buildModule (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\lib\Compilation.js:126:9)
    at A:\Users\username\Documents\GitHub\boram\node_modules\webpack\lib\Compilation.js:309:10
    at A:\Users\username\Documents\GitHub\boram\node_modules\webpack\lib\NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (A:\Users\username\Documents\GitHub\boram\node_modules\tapable\lib\Tapable.js:75:69)
    at onDoneResolving (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\lib\NormalModuleFactory.js:38:11)
    at onDoneResolving (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\lib\NormalModuleFactory.js:121:6)
    at A:\Users\username\Documents\GitHub\boram\node_modules\webpack\lib\NormalModuleFactory.js:116:7
    at A:\Users\username\Documents\GitHub\boram\node_modules\async\lib\async.js:726:13
    at A:\Users\username\Documents\GitHub\boram\node_modules\async\lib\async.js:52:16
 @ ./~/electron-debug ^\.\/.*$

WARNING in ./~/electron-debug/license
Module parse failed: A:\Users\username\Documents\GitHub\boram\node_modules\electron-debug\license Unexpected token (1:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:4)
    at Parser.pp$4.raise (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\lib\Parser.js:902:15)
    at NormalModule.<anonymous> (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\lib\NormalModule.js:104:16)
    at NormalModule.onModuleBuild (A:\Users\username\Documents\GitHub\boram\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (A:\Users\username\Documents\GitHub\boram\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at A:\Users\username\Documents\GitHub\boram\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (A:\Users\username\Documents\GitHub\boram\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at A:\Users\username\Documents\GitHub\boram\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
 @ ./~/electron-debug ^\.\/.*$

WARNING in ./~/electron-debug/readme.md
Module parse failed: A:\Users\username\Documents\GitHub\boram\node_modules\electron-debug\readme.md Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
    at Parser.pp$4.raise (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:2756:10)
    at Parser.pp$7.readToken (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:2477:17)
    at Parser.pp$7.nextToken (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:2468:15)
    at Parser.parse (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:515:10)
    at Object.parse (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\lib\Parser.js:902:15)
    at NormalModule.<anonymous> (A:\Users\username\Documents\GitHub\boram\node_modules\webpack\lib\NormalModule.js:104:16)
    at NormalModule.onModuleBuild (A:\Users\username\Documents\GitHub\boram\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (A:\Users\username\Documents\GitHub\boram\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at A:\Users\username\Documents\GitHub\boram\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (A:\Users\username\Documents\GitHub\boram\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at A:\Users\username\Documents\GitHub\boram\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
 @ ./~/electron-debug ^\.\/.*$
Child extract-text-webpack-plugin:
        + 8 hidden modules
```

```
$ npm run dev

> boram@0.3.7 dev A:\Users\username\Documents\GitHub\boram
> electron dist/app


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! boram@0.3.7 dev: `electron dist/app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the boram@0.3.7 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2018-02-01T13_05_02_501Z-debug.log
```

![image](https://user-images.githubusercontent.com/8265238/35679990-f2893406-0726-11e8-9a99-3c30d85299aa.png)

**Comment by Kagami** [comment]
Not sure what's wrong with webpack build. Maybe try to `git pull` in boram dir, I've pushed Windows-related fix recently. Though main sources seems to be built fine.

Also, forgot to say, you need to also set environment variable BORAM_PLATFORM to win64 (`set BORAM_PLATFORM=win64` in cmd), create `bin` directory in boram, download https://yt-dl.org/latest/youtube-dl.exe to `bin` and copy `C:\mingw\local64` to `bin`. That seems to be it.

Also `set NODE_ENV=production` may help with electron-debug errors because that module won't be required.

**Comment by Kagami** [comment]
Huh, just looked at the build script, actually `cp -r C:\mingw\local64 boram\bin\win64`. I.e. copy with rename.

**Comment by emyarod** [comment]
unfortunately, I am still seeing the same results from [this comment](https://github.com/Kagami/boram/issues/24#issuecomment-362260572) after performing those steps. Do you have any ideas on where to go from here?

**Comment by Kagami** [comment]
Did you correctly export `BORAM_PLATFORM` variable? There shouldn't be check for libmpv in win64 build.

**Comment by Kagami** [comment]
You may also edit `webpack.config.babel.js` and change

```
const BORAM_PLATFORM = process.env.BORAM_PLATFORM || "lin64";
```

to

```
const BORAM_PLATFORM = "win64";
```

if that would be easier. (And also `BORAM_DEBUG` to `false` to eliminate `electron-debug` dependency to avoid warnings.)

**Comment by emyarod** [comment]
>Did you correctly export `BORAM_PLATFORM` variable?

Turns out I wasn't! `set BORAM_PLATFORM=win64` etc in cmd didn't seem to be working, and unless I'm mistaken, I have to execute `$ NODE_ENV=production BORAM_PLATFORM=win64 npm run dev` every time. The environment variables don't persist I guess? In any case, I can finally get things up and running (without editing the webpack config too). Thanks a lot for your help

**Comment by emyarod** [comment]
doing a fresh install, I'm getting errors during node modules installation again since node-gyp is unable to open `libmpv.dll.a`, which doesn't seem to be created during the mpv build anymore. [this may be related?](https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md#linking-libmpv-with-msvc-programs)

```sh
$ rm -rf node_modules/ && npm i

> electron@1.8.8 postinstall E:\Users\username\Documents\GitHub\boram\node_modules\electron
> node install.js


> jss@9.8.7 postinstall E:\Users\username\Documents\GitHub\boram\node_modules\jss
> node -e "console.log('\u001b[35m\u001b[1mLove JSS? You can now support us on open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/jss/donate\u001b[0m')"

Love JSS? You can now support us on open collective:
 > https://opencollective.com/jss/donate

> boram@0.5.6 install E:\Users\username\Documents\GitHub\boram
> node-gyp rebuild


E:\Users\username\Documents\GitHub\boram>if not defined npm_config_node_gyp (node "C:\Users\username\scoop\persist\nvm\nodejs\v13.8.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\username\scoop\persist\nvm\nodejs\v13.8.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  interop.cc
LINK : fatal error LNK1104: cannot open file 'libmpv.dll.a' [E:\Users\username\Documents\GitHub\boram\build\boram.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\username\scoop\persist\nvm\nodejs\v13.8.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\username\\scoop\\apps\\nvm\\current\\nodejs\\nodejs\\node.exe" "C:\\Users\\username\\scoop\\persist\\nvm\\nodejs\\v13.8.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Users\username\Documents\GitHub\boram
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! boram@0.5.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the boram@0.5.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2020-02-17T07_47_36_484Z-debug.log
```

**Comment by emyarod** [comment]
also seeing the error in the initial post in this thread on macOS 10.15.1, after installing `pepper49`, setting `NACL_SDK_ROOT` env variable, and installing `mpv` with `brew`

**Comment by emyarod** [comment]
@Kagami also seeing the error in the initial post in this thread on macOS 10.15.1, after installing `pepper49`, setting `NACL_SDK_ROOT` env variable, and installing `mpv` with `brew`. is `mpv` now being compiled without something that boram depends on?
